name: Deploy Server
on: [workflow_dispatch]
env:
  FOLDER_NAME: scaled-frames
jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
      - name: Add Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_URL }} >> ~/.ssh/known_hosts
      
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: ${{ env.FOLDER_NAME }}

      # Going into folder, creating an .env
      - name: Create .env file
        run: |
          cd ${{ env.FOLDER_NAME }}
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "DIRECT_DB_URL=${{ secrets.DIRECT_DB_URL }}" >> .env
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env
          echo "SUPABASE_JWT_SECRET=${{ secrets.SUPABASE_JWT_SECRET }}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env
          echo "NEXT_PUBLIC_CLIENT_URL=${{ secrets.NEXT_PUBLIC_CLIENT_URL }}" >> .env
          echo "NEXT_PUBLIC_API_FRAMER_URL=${{ secrets.NEXT_PUBLIC_API_FRAMER_URL }}" >> .env
          echo "NEXT_PUBLIC_API_FRAMER_PORT=${{ secrets.NEXT_PUBLIC_API_FRAMER_PORT }}" >> .env
          echo "EC2_URL=${{ secrets.EC2_URL }}" >> .env

      - name: Transfer Repository to EC2
        # Copying over only what has changed
        run: |
          cd ${{ env.FOLDER_NAME }}
          rsync -avz --exclude 'node_modules' --exclude '.git' --exclude '.env.local' --exclude 'apps/framer' --exclude 'apps/framer-e2e' \
            -e "ssh -i ~/.ssh/id_rsa" . ubuntu@${{ secrets.EC2_URL }}:~/framer
      
      - name: Update install
        run: | 
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_URL }} << 'EOF'
            echo "--- Installing NPM"
            cd framer/
            npm install
            echo "--- Generate Prisma data"
            npm run generate
            
            echo "Restarting ec2 Services"
            sudo systemctl daemon-reload
            sudo systemctl restart myapp.service
            sudo systemctl restart caddy
          EOF