name: Deploy Server
run-name: Deploy Server. Run by ${{ github.actor }}
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
      - name: Add Known Hosts
        run: |
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts
      
      - name: Transfer Repository to EC2
        run: |
          tar -czf repo.tar.gz .
          scp -i ~/.ssh/id_rsa repo.tar.gz ${{ secrets.EC2_HOST }}:~/repo.tar.gz

      - name: Extract Repository on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_HOST }} << 'EOF'
          tar -xzf repo.tar.gz -C ~/scaled-frames
          rm repo.tar.gz
          EOF
      
      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "DIRECT_DB_URL=${{ secrets.DIRECT_DB_URL }}" >> .env
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env
          echo "SUPABASE_JWT_SECRET=${{ secrets.SUPABASE_JWT_SECRET }}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env
          echo "NEXT_PUBLIC_CLIENT_URL=${{ secrets.NEXT_PUBLIC_CLIENT_URL }}" >> .env
          echo "NEXT_PUBLIC_API_FRAMER_URL=${{ secrets.NEXT_PUBLIC_API_FRAMER_URL }}" >> .env
          echo "NEXT_PUBLIC_API_FRAMER_PORT=${{ secrets.NEXT_PUBLIC_API_FRAMER_PORT }}" >> .env
      
      -name: Upload .env to EC2
        run: |
          scp -i ~/.ssh/id_rsa .env ${{ secrets.EC2_HOST }}:~/scaled-frames
      
      - name: Run build/deploy script on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_HOST }} 'bash ~/deploy.sh'